### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gmoulin** [DarthMarcius/img-tinify#1]
I tried to install the plugin on a Windows 7 virtual machine.
Installed nodejs (LTS and last version)

installed the plugin using 
npm install -g img-tinyfy

then run the setkey command and got:
![tool_ko](https://cloud.githubusercontent.com/assets/688073/17661953/93f95db0-62e2-11e6-858c-4a3bff29c7bb.png)

tested other commands, similar errors are occuring

**Comment by DarthMarcius** [comment]
I have an idea what is this error about, will look into it now

**Comment by yolo2013** [comment]
You can try [https://github.com/yolo2013/tinyfy-image](https://github.com/yolo2013/tinyfy-image.)
I was just publish it today.

**Comment by DarthMarcius** [comment]
Solved
